import StyledComponentsRegistry from '@/lib/registry'
import '../globals.css'

export const metadata = {
  title: 'Login',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`px-14 py-8  h-screen w-screen bg-pink-500`}>
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
